### ISSUE TITLE
Save rulesDirectories per rule while reducing configuration

### ISSUE THREAD

**Issue by ajafff** [ajafff/wotan#4]
consider:

```yaml
# npm package 'base' /main.yaml
rulesDirectories:
  foo: foo # resolves to foo@1.0.0
rules:
  foo/foobar: error
  foo/baz: error
```

```yaml
# .wotanrc.yaml
extends: base # resolves to main.yaml from above
rulesDirectories:
  foo: foo # resolves to foo@2.0.0
rules:
  foo/baz: error
```

The reduced config is something like
```json
{
  "rules": {
    "foo/foobar": { "severity": "error", "rulesDirectories": ["/node_modules/base/node_modules/foo/rules"] },
    "foo/baz": { "severity": "error", "rulesDirectories": ["./node_modules/foo/rules", "./node_modules/base/node_modules/foo/rules"] },
}
```
This resolves to `foo@1.0.0/foobar` and `foo@2.0.0/baz`
